### ISSUE TITLE
Proposals page: add voting outcome data

### ISSUE THREAD

**Issue by RichardRed0x** [decred/dcrdata#1287]
I have been using the [proposals page ](https://alpha.dcrdata.org/proposals) to find proposal charts, if it had information about proposal voting outcomes (numbers of votes, approval % etc,) it would be a very useful page.

**Comment by buck54321** [comment]
I'd like to see the /proposals and /agendas page come together into a single governance portal different than but closer to the design of voting.decred.org. Likewise, the /agenda and /proposal pages could either be reduced to a single page, or at least adopt some common styling. 

If I don't hear any objections to that plan, I'm going to start working on it as early as this weekend.

**Comment by chappjc** [comment]
Thank would be great for sure.  Go for it!

**Comment by buck54321** [comment]
Your understanding in #1 is correct, but not the solution we need right now. Let's just get the approval % and vote count in the table on  `/proposals` for now. Don't remove it from `/proposal/{token}`. The information is arguably the most important figure associated with the proposal, so it deserves some space in the `/proposals` table too. 

I think that data is already available in the `ProposalInfo` (embedded from `ProposalVotes`) from `gov/politeia/types` being used [in `proposals.tmpl` here.] (https://github.com/decred/dcrdata/blob/71bb36a72193bb61f8bd4882d14d5d06a0aaa1ff/views/proposals.tmpl#L116) Just need to add the columns.

**Comment by njirap** [comment]
ok got it..Thanks

**Comment by njirap** [comment]
@buck54321 is the next iteration of this issue to have `/agendas` and `/proposals` as one page?

**Comment by buck54321** [comment]
That is the plan. I imagine that being a pretty large undertaking that will also involve some consolidation of types from the `gov` packages. That's not to say that you can't work on it. Please do. I just want to make sure that we're attacking it from the best angle. 

For a new page, it might be good to work together on some kind of wireframe or prototype before we get too deep. Can anybody recommend a good open-source mockup/prototyping tool? 

@njirap, have you worked with bootstrap CSS? If not, it might be an informative project for you to make the table on `/proposals` mobile-friendly, which will require you to use the Bootstrap and make some hard decisions about how to best display things in the table. The work would carry over to the combined page as well. We could collab on a mockup while making incremental improvements to page elements before finally combining things.

Another thing to note is that we could potentially be getting some direction on this from @linnutee and the design team (see #1191 and https://github.com/decred/dcrdesign/issues/139), but it's been some time since there was any movement on that, so we should definitely not wait to do awesome things.

**Comment by njirap** [comment]
@buck54321 I can work on making the `/proposals` page mobile friendly. On how to best display things in the table I think I will just work it into the image and likeness of the other views that are already mobile friendly I don't think it's good to deviate too much from what is already set

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/1348.
@buck54321 and @njirap Let's make a new issue for further work on the gov pages.
