### ISSUE TITLE
Serve some results piecemeal via websocket (not API if possible)

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdata#220]
Pages like address search are somewhat controlled presently by having it limit the number of tx shown, although this makes it less useful of course.  But transactions like the airdrop in block 1 are enormous for a browser to render.

It's important to note here that handling this transaction server-side takes around 150ms to process and transfer, but the browser just hangs up trying to deal with that many rows.

There are many such transactions that need a solution.

**Comment by raedah** [comment]
Can be done with pagination like is used on the blocks view so the output can be specified by the user with parameters. /explorer?height=174853&rows=20

**Comment by chappjc** [comment]
Indeed that's a possibility, but I like a smooth transition from one click to the next and that reloads the page.  I think there are some other clever tricks with fragments and click journal (or something like that), which can be read by js to load something from ws.  Or there can just be a button that runs js.

@gozart1 what do you think makes sense here?

**Comment by raedah** [comment]
Im all good with divs and buttons. Just dont like having scroll/mouse be the input behaviour for the user to access data.

**Comment by chappjc** [comment]
Yeah I hate that lazy load in scroll crap.

**Comment by gozart1** [comment]
I like the idea of keeping it fully functional without js.
So basically a page param and an optional size param
Something like 
`/explorer/address/DsnFvuqv1WhXeV6bEFYmf26aYogY9THUmzk?page=1&size=100`
would load the first 100 rows.

For styling I think bootstrap has us covered.
https://v4-alpha.getbootstrap.com/components/pagination/
I think it makes sense to locate it directly above the table so you can page through efficiently without having to your mouse or finger to a new location after every page.

I don't see much need for JS since the backend is so fast anyways.

**Comment by gozart1** [comment]
We can always add [turbolinks](https://github.com/turbolinks/turbolinks) to get those silky smooth transitions once we've got a solid server side rendered setup complete.

**Comment by chappjc** [comment]
Ooh turbolinks looks nice.

Bootstrap pagination wouldn't help much since all the data has to be loaded in one shot.  Unless it's the rendering that's the issue, but I think the table processing would be something.

**Comment by RogueElement** [comment]
I think this should be closed.
