### ISSUE TITLE
gui issue roundup

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#290]
Blocks page:
-Transaction fees are often showing 6, 4, or 2 decimal places. Expected is 8.
-Vote last block valid and choice id info should be cap. So instead of true false, True False, and instead of yes no abstain, Yes No Abstain.
-Size row across all sections could be in alignment on the right side.
-'api' link at the top would be better labeled as 'view decoded'
-Since we moved the block reward to its own section, the transaction list can now be empty. It should be displayed the same as the other empty sections. https://explorer.dcrdata.org/block/0

Landing page:
-Change 'Ticket Window Progress' to 'Current Ticket Window'
-Change 'Block Reward Adjustment Progress' to 'Current Block Reward Adjustment'

Ticket page:
-Maturity bar counter is not being updated with websockets.

Transaction page:
-Instead of saying true/false under then Spent column, instead say spent/unspent
-Create a special case page for the unviewable transaction in the genesis block
https://explorer.dcrdata.org/block/0
-Display type of Ticket or Vote more prominently.

Address page:
-Says, '3 funding transaction' when it should be plural. I also think this font is too small.
-Seems odd that we are only counting funding transactions, rather then all the transactions we are displaying. https://explorer.dcrdata.org/explorer/address/Dsa6QnM7fqkzfrEqzNbHrBtSvsHrd5NheoP  
I imagine that on a page with more transactions it would break the pagination, such as https://explorer.dcrdata.org/explorer/address/Dcur2mcGjmENx4DhNqDctW5wJCVyT3Qeqkx?n=30&start=3290
-On the page for Dcur2mcGjmENx4DhNqDctW5wJCVyT3Qeqkx add a special note that says Development Subsidy. This could be a generalized feature to provide labels on significant accounts.
-Next and Previous buttons could use some keyboard navigation, N and P.

**Comment by chappjc** [comment]
The "funding transaction" issue is tricky, partly because the database scheme, but also because of the "from address" misconception and how I think we should approach it.

Regarding the idea of a "from address", we know that transactions are not spending addresses, but rather specific previous transaction outputs.  So really you can only _pay to_ an address but not _spend from_ an address.  This leads to the design of the address table.

The address table is a giant index of transaction outputs, with one receiving address on an address table row.  The columns include: the address (again, payed to), other output information such as output index and value, this (funding) tx hash, and then... if there is a tx spending the output on this row... that spending tx's hash and info.  Thus, a sql query by address will return rows in this table, where the spending tx columns will be null if the output is unspent.  With this table design, a LIMIT is limiting the number of *funding transactions*.

Alternatively, an address table could have been made where each row is simply an occurrence of an address in a tx output or in a tx input's previous output.  I liked having a row refer only to a tx output, where spending tx info may or may not be present, but it will be in the same row, with the funding tx info.

**Comment by raedah** [comment]
Sounds like it could be a case to JOIN to the table to itself, where the output=input, and that would derive the outputs correlated address.

**Comment by chappjc** [comment]
@raedah So much has changed in 4.0 that I suggest closing this and creating a new issue for specific items to address.
