### ISSUE TITLE
Rich list

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#296]
Though I do not find this data terribly interesting, there have been some requests for it and it seems easy to do. A list of addresses sorted by largest amount first.

**Comment by xaur** [comment]
Well, we now have this: [dcr.observer](https://dcr.observer/) ([source](https://github.com/Cybourgeoisie/dcr-observer), [reddit](https://www.reddit.com/r/decred/comments/7i6ehn/decred_observer_realtime_dcr_rich_list_voting/)), but it wouldn't hurt to have another richlist in dcrdata, because a) dcrdata works without javascript (hence is awesomely great) and b) richlist is a common feature for block explorers.

**Comment by raedah** [comment]
Closing due to general aversion to this feature from the community.
