### ISSUE TITLE
API endpoint that returns the balance of the development fund

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#298]
Do we have this?
If not, we need it. Coinmarketcap is requesting it for the measure of showing coins that are not in circulation.

**Comment by mcalfin** [comment]
will this ever get done?

**Comment by dajohi** [comment]
I bet yes.  What do you bet?

**Comment by mcalfin** [comment]
I bet no unless I take it upon myself, but it would be nice to have publicly available so I don't have to maintain anything myself...

**Comment by dajohi** [comment]
How would you like to help so this issue is resolved sooner?

**Comment by chappjc** [comment]
@mcalfin Yes, it will get done.  Work is not hard, and similar to the recent Insight API PR:

1. The regular API needs to get hooked into the PostgreSQL backend
2. The address endpoint and return data type needs to be modified to request and return address balance in addition to the other stuff.

I have a lot to do, but I will look at this tonight.

**Comment by mcalfin** [comment]
thanks @chappjc much appreciated. 

As soon as it is finished I will make sure CMC gets notified and updated ASAP.

**Comment by chappjc** [comment]
Yeah, true.  All the the project subsidy coins are in fact in circulation, as much as any other active address anyway.

**Comment by mcalfin** [comment]
Thats not how CMC defines circulating supply, but regardless.... will be nice to have this ability since the other block explorer takes nearly 30 seconds to get a response from the API.

**Comment by davecgh** [comment]
I'm going to call that notion out every time I see it mentioned, because it simply makes no sense.  The project subsidy is used to pay for contractors and services.  The recipients are free to do whatever they wish with those coins such as putting them onto exchanges, spending them on goods and services, holding them, or staking them.  The coins have no special locking provisions associated with them and are not otherwise encumbered by anything such a time locks. They can change hands at any time.

**Comment by chappjc** [comment]
resolved by PR #432
