### ISSUE TITLE
Full transaction list in address view with postgres

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#327]
Jon Chappelow [11:15 PM]
In full mode, with psql, we get the transactions for a certain address by querying the `addresses` table, which is structured as follows...
each row is an occurence of an address in a certain transaction output
So there are multiple rows in this table for a given address
Thus, getting all the rows for a given address provides you right away with all the *funding transactions*
A spending transaction is defined as a transaction that spends one of these outpoints.  Because we want to simulate the concept of a balance for an address, we record these spending transactions in the addresses table as additional columns (edited)
So each row has 0 or 1 spending transactions, just as a transaction outpoint may only be spent once
If the spending transactions _columns_ are still `NULL`, then it is a UTXO (unspend transaction outpoint)
If there is spending txn data in those columns for some row, then that outpoint (funded via some address we're interested in) is spent
It's nice because when you get a row, you potentially get two transactions: the one that funded that outpoint (w/ an address) and one that spent that outpoint
This is very logical to me and reflects how coins actually flow in Decred (and Bitcoin, etc.)
With the `searchrawtransactions` RPC, it pulls any txns but it's really confusing.

I'm looking at how we use `SearchRawTransactionsVerbose` for a solution, but there's nothing simple or quick
If the 10 most recent transactions spend outpoints w/ the given address, those will show first (edited)
But the full mode focuses on funding transactions, which in this example are older
so it would show the 10 most recent funding transactions with any spendingtransactions right below the funding one (paired), and possibly none of the 10 spending transactions that `SearchRawTransactionsVerbose` returned (edited)
The psql addresses table does not even store tx heights, just hash and vout index.  The ordering comes from the query ordering by row id, which is the same ordering as the height that the funding tx would give
2.0 will bring a db scheme change requiring a rebuild of psql, so if we want to add spend height (and recieve/fund height) to the addresses table, we can do that
that would allow us to query w/ "order by spend_height limit 10", for example (edited)
not sure how far that would get us though...
I'd only like to add data to the tables that is actually useful

raedah [3:02 AM]
Each row is an occurrence of an address in a certain transaction output, and we are simply querying the table and getting the corresponding txhash. The same rows being returned also contain the txhash of the spending transaction (which is all the transactions that use that address as the input.) Sounds like we already ahve the complete return set we need, it would just be a matter of including the spending txhash set in the list of transactions we are displaying.
We could add a drop down filter to select (All, Funding, Spending) so that a user could narrow what they are viewing.

Jon Chappelow [3:24 AM]
Yes, we do have the data we need, but the thing is the ordering and how that affects the offset and limit parts of the query (edited)
We use the `...ORDER BY id LIMIT n OFFSET x;` query so we don't get the huge list when we just want n starting at x (edited)
We do show the spending transactions, but just the ones that corresponding to the next N funding transactions (edited)
We can write separate queries for spending and funding, but...
The only order that makes sense for the spending ones is the order from the funding ones of the same rows
https://github.com/dcrdata/dcrdata/blob/master/db/dcrpg/internal/addrstmts.go#L46-L56

raedah [4:00 AM]
Should be able to be done with some joins and perhaps a temp table.

Jon Chappelow [4:18 AM]
To have both spending and funding in the same web page table, there needs to be some common ordering (edited)
The spending and funding are linked, so I just tag on any spending one
Seems like the spend height, or a second query into the transactions transactions table (different table) would be needed
Hmm, but to limit the result from the address table query, some way to order the spend txns separately from the funding ones is needed still

**Comment by dmigwi** [comment]
I have been though the addresses table trying to understand how to fix the above issue and I came to a conclusion that it might not be as simple as it looks.

I ran the query:
```sql
select * from addresses where address = 'TsgKxpRWfFvnuqxZX6Qfx3z6rEYBav1xS9n' limit 10;
```
 using the testnet data and got the data below 

(Screenshot of addresses table).
<img width="1576" alt="screen shot 2018-04-07 at 19 57 22" src="https://user-images.githubusercontent.com/22055953/38458839-30562dfe-3aab-11e8-9742-8a415c6b6de7.png">

I noticed two main issues with the data returned:
 - A spending transaction hash exist in the same row with a funding transaction hash.
 - For every spending transaction hash a new funding transaction hash exists.

In my logical thinking of this, I expected that not all credit in a funding transaction should be spent by a given spending transaction. According to the screenshot above, Does it mean that every funding transaction must be spent in **whole** by a spending transaction? More questions exists on how a given spending transaction is even matched to a given funding transaction as in real life both transactions have a zero chance of possibility of ever happening simultaneously.

Possible Solution.
Have the specific transaction types stored in the address table with each type store on its own row and then have an extra column that differentiates the transaction types. i.e. funding and spending transactions should be stored each in its own row and extra column can hold enums["spending/debit", "funding/credit"] that can be used to differentiate the transaction types.

A second  issue exists in the addresses table which is data duplication. There must have been reasons to as why someone decided to do it this way but it goes against all rules that help in database optimization.

Screenshot of the transactions table
```sql
select * from transactions where id = 585;
```
<img width="1677" alt="screen shot 2018-04-07 at 21 09 03" src="https://user-images.githubusercontent.com/22055953/38459253-29cc5850-3ab0-11e8-8568-954e2b6151d1.png">

Screenshot of the addresses table indicating the duplicate data
<img width="955" alt="duplicate data" src="https://user-images.githubusercontent.com/22055953/38459325-ea757816-3ab0-11e8-97de-e712725c7e50.png">

On the `addresses` table we have duplication of `funding_tx_row_id` and `funding_tx_hash` data which can both be found in the transactions table as `id` and `tx_hash` respectively. To me this goes against all rules of database optimization as one should never have the same set of data in the same database found in multiple tables. This may end up being a source of inconsistencies especially when an update to a specific table fails and another one succeeds.

Possible Solution.
Depending on what is mostly used in the addresses table and may rarely change in case of an update made to the transactions table either `funding_tx_row_id` or `funding_tx_hash` should be dropped from the addresses as maintaining them as it is leads to having tables that consume to much unnecessary storage space which in turn means that money is wasted too.

**Comment by chappjc** [comment]
@dmigwi The `addresses` table is essentially listing transaction outpoints and the corresponding transaction inputs that reference them, if there is a spending transaction.  Notice the index columns, that taken with the transaction hash specify the input or output.

Your concern about spending a transaction in whole should be clear based on this explanation.  A transaction with N outputs paying to addresses will have N rows in the addresses table.

Regarding matching funding to spending, when a transaction occurs that pays to an address, a new row in the table is created with `NULL` values for the spending tx data.  When and if a different transaction is mined, a lookup in the address table is performed for each of the inputs to identify which previous outputs (in the funding_tx... columns) are being spend.  Those rows are then updated with the spending tx data and the columns are no longer null.  Consider these queries:

https://github.com/decred/dcrdata/blob/a356c1f247a8424eb23d5f47759f47d0dbc7d1ad/db/dcrpg/internal/addrstmts.go#L51-L52

The first gets the *unspent* rows for an address because of the `spending_tx_row_id IS NULL` part.  The second gets the *spent* rows for an address because of the `spending_tx_row_id IS NOT NULL` part.

**Comment by chappjc** [comment]
Regarding duplication of data, I agree that it's not optimal.  As you point out, the `funding_tx_hash` does not need to be there (or it could be stored as a 32 bytes instead of 64 characters of text).

However, I think you are misunderstanding `funding_tx_row_id`.  This is the unique row id (serial) of the corresponding transaction in the `transactions` table.  Similarly, the `vout_row_id` is the row id in the `vouts` table, where the details of the output are stored.  Referencing the row id of another table is not the bad kind of duplication; it's what allows us to break up the transaction ins/outs into separate tables up while not repeating all transaction information that is common to the inputs and outputs.  Rather the row ids are pointers to the other tables.

But back to the *tx_hash duplication, it can be removed entirely from the `addresses` table, but then you'd need query the other tables.  It's very likely this can be done efficiently in a single statement, but I don't know how to do it.  This would be valuable to investigate.

**Comment by chappjc** [comment]
Thanks for looking into this BTW!  My knowledge of PostgreSQL is novice level, so I certainly made many mistakes.  I would be happy to see a proposal to redesign the entire tables scheme if it is demonstrated that one would be significantly improved.

**Comment by dmigwi** [comment]
@chappjc I certainly have a lot to learn from you about the current system and the way everything is structured. There is a lot you've accomplished that a novice wouldn't. Away from that, I may have overlooked some issues but still believe that a lot of improvements could be achieved by some small optimizations.

Based on my small understanding about RDMS like postgres, the following  is a new issue that can be improved by my earlier suggestion of having each transaction type in its own row without having null values used.
```
Regarding matching funding to spending, when a transaction occurs that pays to an address, a new row in the table is created with NULL values for the spending tx data.
```
For any column/row intersection (simply a cell) a memory location is reserved whether it is used or not. This means that all cells with NULL values just because a spending transaction was created to a specific address are reserved memory locations that may never be used ever. Having each transaction type in its row and an extra columns that  just to differentiate the transaction types fixes the unused (with Null values) memory locations and also makes it easier to make a query for specific type of transactions thus fixing the main issue.

**Comment by dmigwi** [comment]
Concerning the duplication of data is that if `funding_tx_hash` can be obtained from the transactions table using `funding_tx_row_id` then having `funding_tx_hash` in the addresses table is what I am calling Duplication of data. I have already stated the demerits of having duplicate data thus I should not repeat them.

**Comment by dmigwi** [comment]
By the way this queries may not be offering the correct output as is expected of them and that is why this issue exists in the first place https://github.com/decred/dcrdata/blob/a356c1f247a8424eb23d5f47759f47d0dbc7d1ad/db/dcrpg/internal/addrstmts.go#L51-L52

I am 100% willing to collaborate on this on with you @chappjc. In the meantime I will come up with a sample addresses table design that you review and comment on.

**Comment by chappjc** [comment]
Can you explain about the queries not giving expected results?

**Comment by chappjc** [comment]
> Concerning the duplication of data is that if funding_tx_hash can be obtained from the transactions table using funding_tx_row_id then having funding_tx_hash in the addresses table is what I am calling Duplication of data. I have already stated the demerits of having duplicate data thus I should not repeat them.

Yes, I acknowledged this in my previous response.  The concern I raised is that you need another query to get the hash from the other table.

**Comment by chappjc** [comment]
Let's also be sure to define the problem exactly is.  We're able to query for spending and funding transaction without an issue now.  Test it on the "beta" site:

https://beta.dcrdata.org/address/DsVQbEz2Hxxj96CseVJVBrc6KmERfrCmNow?txntype=all&n=20&start=0

These are the actual statements that get the data:

https://github.com/decred/dcrdata/blob/a356c1f247a8424eb23d5f47759f47d0dbc7d1ad/db/dcrpg/internal/addrstmts.go#L77-L83

**Comment by dmigwi** [comment]
Thanks for point out this https://github.com/decred/dcrdata/blob/a356c1f247a8424eb23d5f47759f47d0dbc7d1ad/db/dcrpg/internal/addrstmts.go#L77-L83
It makes sense.
But what I was pointing out with the earlier queries is that there is a possibility of there not existing a clear difference between a spending and funding transactions and thus outpoints happens. This makes more sense to me as the main reason why the second set of queries fail. Got a better reason to as why the second set of queries fails?

**Comment by chappjc** [comment]
I'm not sure what you mean in this statement:

> there is a possibility of there not existing a clear difference between a spending and funding transactions and thus outpoints happens

Perhaps an example?

**Comment by dmigwi** [comment]
>In this context, what exactly does the word `outpoints` mean? This seems to be the issue we first need to agree on.

Kindly help me understand what outpoint is used in this context to mean.

**Comment by chappjc** [comment]
Oh, regarding "outpoint", please see here: https://bitcoin.org/en/glossary/outpoint
Essentially, and outpoint is tx_hash:output_index
So, a transaction that has 4 outputs will have 4 globally unique outpoints defined as above.  This is really what's happening in the `addresses` table, listing outpoints (funding_*) and the transaction input that reference the outpoint (spending_*).  This works because the coins referenced by an outpoint must be spent in full, and just once.

**Comment by dmigwi** [comment]
Ok. Please help me then understand why you think this queries might by malfunctioning https://github.com/decred/dcrdata/blob/a356c1f247a8424eb23d5f47759f47d0dbc7d1ad/db/dcrpg/internal/addrstmts.go#L77-L83

**Comment by chappjc** [comment]
To add some background to the discussion, the main reason we had to implement this kind of relationship in a persistent DB is because we wanted to put a link to the spending transaction, if any, for each output of a transaction.  For example, see the following transaction, which as of right no has several outputs spent (with links) and some not spent (no link):  https://explorer.dcrdata.org/tx/9c5118ce881fa015c7d759638418301970d9c206e3089b749310a64b676274e7

As I typed, I saw your comment asking about potential causes for a malfunction in those queries.  Presently I think they're fine.  Perhaps the issue discussed originally in this thread is it's a burden to sort the spending transactions in a meaningful way since the row id (serial number) of the address table is only temporally ordered for the funding transactions, not the spending ones.  Hence my suggestion in the discussion pasted into raedah's first post on this issue:

> The psql addresses table does not even store tx heights, just hash and vout index. The ordering comes from the query ordering by row id, which is the same ordering as the height that the funding tx would give
2.0 will bring a db scheme change requiring a rebuild of psql, so if we want to add spend height (and recieve/fund height) to the addresses table, we can do that
that would allow us to query w/ "order by spend_height limit 10", for example (edited)
not sure how far that would get us though...
I'd only like to add data to the tables that is actually useful

**Comment by mikefullman** [comment]
How about this:
note:  Query input variables posted from webpage (aside from address):  post_offset, post_limit

1.  add funding_block_time (bigint) to the addresses table - have this inserted when we process vins
2.  add spending_block_time (bigint) to the addresses table - have this inserted when we process vouts
3.  Query funding transactions 
SELECT	value,funding_tx_hash, funding_block_time FROM addresses WHERE address='Dcur2mcGjmENx4DhNqDctW5wJCVyT3Qeqkx' limit (post_offset+post_limit)
4.  In code scan this table for min_funding_block_time.  This could also be done with a separate group_by query - not sure which one is faster.
5.  Query spending transactions
SELECT	sum(value) as value,spending_tx_hash, max(<spending_block_time>) as spending_block_time FROM addresses WHERE address='Dcur2mcGjmENx4DhNqDctW5wJCVyT3Qeqkx' AND  spending_tx_hash IS NOT NULL AND spending_block_time>min_funding_block_time GROUP BY spending_tx_hash
6.  At this point we have two lists of transactions that we can programatically union together and order by the block time.  this will result in a list of transactions that is guaranteed to be at least post_offset+post_limit long.  After the spending transactions are added in, our list will be longer than post_offset_post_limit and thus we would then just extract the actual post_offset and post_limit from this union list and display the results.

The reason to add the block times to the address table is I found joins to be incredibly inefficient based on the hashes.  They might be inefficient regardless, but at least the way we would need to join into the transactions right now those joins are way too slow.

I was hoping to code this in, but i'm still struggling with corruption in my db created during debugging and trying to sort out the best way setup my dev environment for fast iterations of code.  Meanwhile when the db gets corrupted i just have it start fresh which takes about 16 hours.

**Comment by dmigwi** [comment]
I have managed to fix the sorting issue for both the `SelectAddressDebitsLimitNByAddress` and `SelectAddressCreditsLimitNByAddress` by ordering the output with their respective `block_time` values. `SelectAddressCreditsLimitNByAddress` works fine but `SelectAddressDebitsLimitNByAddress` doesn't appear as expected, as displayed in the screenshot below.

*(column time is not properly ordered)*
<img width="1389" alt="screen shot 2018-04-11 at 19 26 04" src="https://user-images.githubusercontent.com/22055953/38646915-8d853e62-3df2-11e8-8c97-5dc45b34c4f1.png">

`SelectAddressCreditsLimitNByAddress` works fine because we only select funding_tx details but `SelectAddressDebitsLimitNByAddress` selects both funding_tx and spending_tx details. As you can see, the above screenshot fills the whole view since for the 20 spending transactions selected the matching 20 funding transactions were also selected.

Proposed Solution
After having a conversation with @raedah, we thought it wise to possibly change the current addresses table schema so that we can have the spending and funding transactions each take its own 
row. We shall need two extra columns, one holding a boolean value that differentiates the transaction types and the other one holding the row_id that matches the funding transactions output row id that was spent by that specific spending transaction. For the `spending_tx_row_id` and `funding_tx_row_id` we shall switch them with their respective `block_time` values.

Even though this involves quite a lot of work. In the long run, the new Addresses table shall be easy to reason with. We shall easily be able to select what we need and in a meaningful order, without having to use the sql Joins that slow down the queries. While executing `SelectAddressDebitsLimitNByAddress` only the reference (row_id) to the funding transaction output shall be selected instead of selecting the all the details about the funding transactions output.

**Comment by chappjc** [comment]
> SelectAddressCreditsLimitNByAddress works fine because we only select funding_tx details but SelectAddressDebitsLimitNByAddress selects both funding_tx and spending_tx details

Well you can just change the query so `SelectAddressDebitsLimitNByAddress` does not select the funding tx details.

I'm tentatively OK with splitting the funding/spending into separate rows, but I have concerns.

First, by splitting, now we duplicate the columns `address` and `value`, and consume space for an additional serial (another row id).

> We shall need two extra columns, one holding a boolean value that differentiates the transaction types and the other one holding the row_id that matches the funding transactions output row id that was spent by that specific spending transaction. 

Let's not think of this as "transaction types" but rather "input or output".  Keep in mind this is _not_ a transactions table.  It lists tx outpoints for addresses, and (presently) any tx input that consumes it.

Any new `other_row_id` column should be bidirectional.  That is, for a tx outpoint, the `other_row_id` should give the row of the corresponding input if there is a spending transaction.  For a tx input, the `other_row_id` should give the row for the outpoint that it is consuming.

At this point, why not just replace `addresses` table with `inputs` and outputs` tables, or augment the existing `vins` and `vouts` tables where they are already separate.  For reference, here's the structure of these two existing tables:

https://github.com/decred/dcrdata/blob/c933ac431324001d382b541f7a13906296cf3c4c/db/dcrpg/internal/vinoutstmts.go#L14-L22

https://github.com/decred/dcrdata/blob/c933ac431324001d382b541f7a13906296cf3c4c/db/dcrpg/internal/vinoutstmts.go#L74-L85

The `vins` table is how we presently get the spending transaction (true/false, plus a link) for each tx output on the transaction page.  To be honest, I don't think we're using `vouts` except in pgblockchain_test.go.

**Comment by chappjc** [comment]
BTW, I think that does appear as expected.  The whole idea was show the spending tx info on the row immediately below the funding.  However, when _just_ showing the debits/spending, that's when a different order is needed.

**Comment by chappjc** [comment]
Nevermind the idea of augmenting the `vins` and `vouts` tables.  The `vouts` table is very different because a single output's PkScript may encode multiple addresses.  Hence the `addresses` table.

**Comment by chappjc** [comment]
@dmigwi Cool.  In my comments I partly aim to clarify for anyone else following this discussion.  I was pretty sure you were clear about it.

Regardless of how this page "should" show a merged list of credits/debits, it's good to think about a following page that would show actual transactions relevant to an address, whereby you would not want to see multiple rows with the same txid and only different in/out indexes.  What value to show in this case is not clear, but my vote would be the net change in "balance" for the address as a result of the transaction. 

Also, at least having the ability to "unbind" the spending tx from the funding tx on the table, and instead sort everything - merged - by block time should certainly be a capability.  As we can see now, having the limit and offset thrown in there is what makes this tricky.

I'm looking forward to seeing what you guys come up with in practice.

**Comment by dmigwi** [comment]
@chappjc I hope you still support switching spending_tx_row_id and funding_tx_row_id with their respective block_time values to eliminate the sql joins they maybe needed to order the data using the block_time values.

**Comment by chappjc** [comment]
> This is confusing as I can't tell if txid as used here is similar to the tx_hash for a given input/output. I also thought that every tx input/output has a unique value of the tx_hash or txid if they mean the same thing. @chappjc would you mind explaining more on this including what "balance" is used to mean here.

Correct.  txid is tx_hash, just easier to type.  :)

Inputs can be specified by the pair (tx_hash, input_index), similarly outputs by (tx_hash, input_index).

I should have said total unspent, or sum of unspent outputs, instead of balance.

> What should be given more priority between decoupling the addresses funding/spending tx inputs/output or just maintaining the current schema and make changes to the Go code if need be?

That is a good question.  The answer is whatever makes for a simple and understandable implementation without impacting performance severely.  Likely this is splitting putting funding/spending on different rows as you suggest, but I believe the change @mikefullman suggested is worth investigating too.  Changing the db schema is perfectly OK if we maintain all existing functionality.

> I hope you still support switching spending_tx_row_id and funding_tx_row_id with their respective block_time values to eliminate the sql joins that may be needed to order the data using the block_time values.

I'm not totally clear on this actually.  I agree we need block_time to do what we want without referencing the transactions table, but I still think we may need the `*tx_row_id` columns if we want to quickly reference the transactions table.  Although the transactions table is indexed by tx_hash too, I suspect queries in transactions by the serial is faster than tx_hash even though they are both indexed.  Perhaps not though.

**Comment by mikefullman** [comment]
I prototyped the concept and it seems to work great.  Query speeds are fast.  My DB is still indexing Vouts so the total balance is not right still but the order and summing seems right.

DB changes are:
1.  add spending_tx_time on addresses
2.  add funding_tx_time on addresses
3.  add tx_time on vins (only required during bulk import)

![image](https://user-images.githubusercontent.com/11194546/38845706-9c38ae94-41ad-11e8-8019-75749816c900.png)

I'll prep a PR for it like @dmigwi has done with PR427 if you want.  From there we can decide which direction to go.  I could do a lot of trimming of code as well in these sections.  There are quite a few orphaned functions and commented code laying around.

**Comment by chappjc** [comment]
@mikefullman Don't worry about making it pretty.  Benchmarks are off interest though.  There address page needs to be resilient and robust to DoS

**Comment by chappjc** [comment]
Just to be clear, I think it's likely @dmigwi 's approach in PR #427 will be our choice, but I also would like to be sure we are going with an option that is both fast and simple

**Comment by mikefullman** [comment]
@chappjc Yep, I understand.  I like the simplicity of that approach as well, I'm not sure what issues lurk in that new architecture yet as I don't fully understand the entire design.  Surely there is a good reason why inputs are matched to outputs in the address table :)

Lets see how things roll out.  I just proposed to @dmigwi that I update my transaction function to output data in roughly the same format as @dmigwi 's table and then finish out the rendering.  Maybe that will help both approaches.

**Comment by chappjc** [comment]
resolved by PR https://github.com/decred/dcrdata/pull/427
