### ISSUE TITLE
Display information about orphan blocks and reorgs

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#338]
Research how we can display information about orphan blocks and sidechains.

**Comment by chappjc** [comment]
This may be doable with SPV, when that's added to dcrd.  Right now all an RPC client knows about is the main chain and what it once though was the main chain prior to reorg.

**Comment by raedah** [comment]
related to https://github.com/dcrdata/dcrdata/issues/56

**Comment by chappjc** [comment]
Now doable with the recently-added `getchaintips` RPC:

````
getchaintips

Returns information about all known chain tips the in the block tree.

The statuses in the result have the following meanings:
active: The current best chain tip.
invalid: The block or one of its ancestors is invalid.
headers-only: The block or one of its ancestors does not have the full block data available which also means the block can't be validated or connected.
valid-fork: The block is fully validated which implies it was probably part of the main chain at one point and was reorganized.
valid-headers: The full block data is available and the header is valid, but the block was never validated which implies it was probably never part of the main chain.

Arguments:
None

Result:
[{
 "height": n,       (numeric) The height of the chain tip
 "hash": "value",   (string)  The block hash of the chain tip
 "branchlen": n,    (numeric) The length of the branch that connects the tip to the main chain (0 for the main chain tip)
 "status": "value", (string)  The status of the chain (active, invalid, headers-only, valid-fork, valid-headers)
},...]
````

**Comment by chappjc** [comment]
This can now be done properly given:

1. Side chain recording in https://github.com/decred/dcrdata/pull/580
2. The `getchaintips`.

I'm assigning myself.

**Comment by chappjc** [comment]
PR https://github.com/decred/dcrdata/pull/654 uses new queries to show side chain blocks.  These blocks are presently only known because they were previously main chain prior to a reorg.

The next step in this task is to use the `getchaintips` RPC to get information about side chain blocks known to dcrd.  Some of these may intersect with those recorded by dcrdata.  Others returned by dcrd that were not already recorded by dcrdata may be then be retrieved (hopefully).  My understanding is that transactions in blocks with `"status"` of `"valid-headers"` or `"valid-fork"` may be retrieved for processing.

**Comment by chappjc** [comment]
The best fix possible is implemented in https://github.com/decred/dcrdata/pull/717.  With that, any side chain blocks may be loaded in dcrdata.

However, as I mentioned, it will not be possible to find a side chain block if dcrd was not up and running when that fork happened.  The fork must be observed by dcrd.  A fresh sync of dcrd will lose all record of side chain blocks previously recorded.
