### ISSUE TITLE
Address view filter

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#377]
On the address view, include a filter selector.
All
Credits
Debits
SSTX

Function in lite mode and full mode.

**Comment by chappjc** [comment]
💯
One I'd like to hit up, given a chance.  I'll see

**Comment by chappjc** [comment]
PR #385 does it for full mode.  Lite mode needs an entirely different approach since all we can do is searchrawtransactions, not arbitrary queries.

**Comment by raedah** [comment]
For lite mode I suggest pulling up to x (1000) and filtering those. This would be in line with existing policy and warnings displayed to users, and would be useful for the large majority of cases that have less then 1000 txs in an address. Though I dont consider extending features on litemode a high priority.

**Comment by chappjc** [comment]
That would work, but it would hobble the address page.  Doing a search for with a limit of 1000 it slow when there are at least 1000 to look through.

For addresses w/ many funding transactions and not so many spending transactions, it would be bad no matter how clever we got with starting small and increasing the limit since it would have to repeatedly fetch them all just to see if there are spending transactions, not just funding.  Eventually it would have to search up to 1000 just to see that there aren't any.
