### ISSUE TITLE
Transactions return 0 confirmations and no timestamp until 2 confirmations

### ISSUE THREAD

**Issue by vctt94** [decred/dcrdata#401]
When creating a transaction, it returns 0 confirmations and no timestamp until it has 2 confirmations.

**Comment by raedah** [comment]
related to 
https://github.com/decred/dcrdata/issues/130
https://github.com/decred/dcrdata/issues/142

**Comment by chappjc** [comment]
This is a dcrd issue that we have to work around.  The issue is that after a transaction has been mined in a block, it is _confirmed_, but not until the next block with the votes for the block in which it is mined is the transaction _validated_ too.

A resolution would be special handling for transactions with just 1 confirmation.

**Comment by chappjc** [comment]
Ref. decred/dcrd#1471
