### ISSUE TITLE
missing ticket info

### ISSUE THREAD

**Issue by JFixby** [decred/dcrdata#658]
https://explorer.dcrdata.org/tx/7950012a02e188c40159bcea264f797934f084fdb8ea71e8d29099eb793d30e7

https://explorer.dcrdata.org/tx/736d0790deaaca27a9363c21c6c285c249ff73d7222a8ddc7048dbaeaf8dab09

Expected: 

![image](https://user-images.githubusercontent.com/1580663/44947629-0b792a80-ae10-11e8-92b7-1bb9d67d773c.png)

Actual:

![image](https://user-images.githubusercontent.com/1580663/44947631-17fd8300-ae10-11e8-8587-43071dc87608.png)

**Comment by papacarp** [comment]
I worked a lot on this in the spring.  I'm not exactly following what is missing.  In the actual screenshot you are showing a missed ticket.  In the other one you are showing a live ticket.  The live ticket has the bar graphs because its live.  Are you expecting to see the bar graphs for the missed ticket - even though it didn't vote?  Since missing a vote is the end of that ticket I think the bar graphs should not be on missed tickets.  Maybe I'm just not understanding...

**Comment by JFixby** [comment]
The ticket on the second screenshot is live, but the bar graphs are missing.

**Comment by JFixby** [comment]
Anyway, seems like `dcrwallet` malfunction.
