### ISSUE TITLE
mempool.tmpl expects snake case key, but backend serves in camel case

### ISSUE THREAD

**Issue by gozart1** [decred/dcrdata#827]
mempool.tmpl has code to render table rows that expects snake cased keys.
Eg `tx.vote_info.block_validation.height`
<img width="709" alt="screen shot 2018-11-19 at 12 57 49 am" src="https://user-images.githubusercontent.com/25571523/48696291-5fd1b200-eb96-11e8-9bf6-25bded52da41.png">

But websocket api serves the data in camel case `tx.VoteInfo.block_validation.height`
And this causes websocket updates to error out.

<img width="1031" alt="screen shot 2018-11-19 at 12 54 48 am" src="https://user-images.githubusercontent.com/25571523/48696302-63fdcf80-eb96-11e8-86ed-60499e45c0f9.png">

Which way should the keys be cased?

**Comment by chappjc** [comment]
All the types in explorertypes.go (e.g. `TrimmedBlockInfo`, `TrimmedTxInfo`, etc.) should have `json:` tags so they are in snake case.  I think camel case is not idiomatic in JSON/js.

**Comment by buck54321** [comment]
What's standard/idomatic seems to depend on who you ask. In general, if the structure is intended to be parsed as a  javascript object using `JSON.parse`, I think camel case is okay as it results in javascript objects with camelcase property names, while if it is intended for display (`apitypes`), snake case may be okay. Interestingly, `dcrd/dcrjson` does neither, opting to drop any delimiting standard between "words" and just using lowercase without spaces. 

It may also be appropriate to differentiate between lower and upper camel case, e.g. camelCase vs CamelCase, the latter of which I rarely see in JSON. 

Because of the ambiguity in the JSON standard, I think it might be okay to remain a little lax on our internal standards in this case, perhaps just having a loose recommendation instead.

**Comment by chappjc** [comment]
I could be persuaded to go either way, but since our api types are already snake_case, it would seem to be wiser to stick with that, especially since we don't have a versioned API that allows consumers to choose the version.

For use with actual javascript, camelCase is ok, but for formatted API responses in json text, I would prefer to stick to snake case.  That would be my recommendation.

**Comment by gozart1** [comment]
I'm all for consistently snake casing field names in our json apis.

One benefit of this is that when reading code of a js application ( where the **variables** are all camel cased ) it provides a hint to the reader about a given datums origin ( front or backend ).

**Comment by buck54321** [comment]
Related: It looks like #718 changed the response type for the `getmempooltxs` websocket response from `MempoolInfo` to `TrimmedTxInfo` which broke the mempool page new block handling.

**Comment by chappjc** [comment]
Is this a wrap, or do the remaining pages need to be reworked first?

**Comment by buck54321** [comment]
This is not an issue for the mempool page anymore . There are still some inconsistencies in our handling of JSON via websocket, but this issue can be closed, I think.
