### ISSUE TITLE
span element with two Stimulus.js targets

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdata#889]
The last block age `span` element does not work properly.

`(<span data-target="mempool.bestBlockTime time.age" data-age="{{.LastBlockTime}}"></span> ago)`

Can an element define two targets like that?

`LastBlockTime` seems to be OK on page load.

The way the mempool controller updates `bestBlockTarget` and `bestBlockTimeTarget` also seems questionable:

```js
$(this.bestBlockTarget).data("hash",m.block_hash)
$(this.bestBlockTarget).attr("data-hash",m.block_hash)

$(this.bestBlockTimeTarget).data('age', m.block_time)
$(this.bestBlockTimeTarget).attr('data-age', m.block_time)
```

**Comment by buck54321** [comment]
I am unable to reproduce the issue, but I may have found something. 

Stimulus does support multiple targets on the same element, as well as multiple controllers. The `data-controller` elements are nested, which is a little questionable, but it seems that [it is supported](https://discourse.stimulusjs.org/t/are-recursive-controllers-explicitly-supported/421). Regardless, we can match the implementation up with the docs so there's no need to wonder. Instead of nesting, the body should be given

```
data-controller="mempool time"
```

The jQuery `.data()` vs `.attr('data-*')` is definitely an issue, and I've seen it causing a problem one other place. Apparently jQuery `.data()` can have some un-intuitive behavior. See [this stackoverflow question](https://stackoverflow.com/questions/7261619/jquery-data-vs-attr) for a taste. All of this should be swept out with the rest of the jQuery, and native `dataset` used instead.

**Comment by chappjc** [comment]
On https://explorer.dcrdata.org/mempool, it looks like this:

![image](https://user-images.githubusercontent.com/9373513/50103251-d8a34880-01ec-11e9-9c0a-878b7525ea26.png)

It looks fine on alpha, so it must be a 3.1 issue.

**Comment by chappjc** [comment]
Ah, wrong controller.  I'll switch it back from `time.age` -> `main.age`.  Good find, thanks.

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/891
