### ISSUE TITLE
Tx not included in stakeholder-approved mainchain

### ISSUE THREAD

**Issue by roccomuso** [decred/dcrdata#965]
I'm new to Decred. Can someone explain what
> This transaction is not included in a stakeholder-approved mainchain block.

exactly means?

**Comment by chappjc** [comment]
That's a good question.  In the context you are receiving the message (the transaction page), it means that the transaction is in a block that either:
- was not approved by stakeholders (via votes), thus invalidating the transaction.
- was reorganized off the main chain.

Both cases are normal and by design, although not terribly common (especially the first), and in both cases you can make the transaction again.

Refs:
- https://docs.decred.org/glossary/#reorg
- https://docs.decred.org/glossary/#proof-of-stake-pos-voting
- https://docs.decred.org/faq/proof-of-stake/general/#9-what-is-proof-of-stake-pos-voting

**Comment by chappjc** [comment]
To determine which case it was, look at the "INCLUDED IN BLOCK" part of the transaction's page.  It may says there that it is a side chain block (meaning likely reorg).  You can then click on the linked block and it will tell you more.

**Comment by xaur** [comment]
> was not approved by stakeholders (via votes), thus invalidating the transaction.

Do you mean lack of votes or explicit No votes?
