### ISSUE TITLE
home: make left and right blocks of same height

### ISSUE THREAD

**Issue by xaur** [decred/dcrdata#992]
Increase the number of rows in Blocks and Mempool sections so that together they occupy same height as Voting+Mining+Distribution on the right.

Suggested [here](https://www.reddit.com/r/decred/comments/anu91e/new_decred_block_explorer_by_dcrdataorg/efxtg21/).

![](https://i.imgur.com/5KRrn6I.jpg)

**Comment by gozart1** [comment]
responded to that reddit thread, but tldr: 
- Exchange rate on its own row was a layout bug thats been fixed
- Let's wait and see how the table style refactor shakes out, then can revisit this and explore options. Eg. Instead of adding more rows, the height of table rows could be increased for large screens, so that the overall layout is more rectangular in full size mode.
